term.clear()
term.setCursorPos(1,1)
print("Welcome to the CosgOS command prompt!")
print("Type \"back\" to go back to the main menu.")
print("Type \"install [filename] [displayname]\" to add files to the Applications menu")
print("---------------------------------------------------")
shell.run("shell")
